#!/usr/bin/env python

from prometheus_client import start_http_server, REGISTRY
import time
import argparse
from trafficserver_exporter.collector import TrafficServerCollector

ARGS = argparse.ArgumentParser(
    description="trafficserver exporter for Prometheus")
ARGS.add_argument(
    '--endpoint', dest='endpoint', default='http://localhost/_stats')
ARGS.add_argument(
    '--port', dest='port', default=9122)


def main():
    """Main program.

    Parse arguments, start webserver to serve /metrics.
    """
    args = ARGS.parse_args()

    start_http_server(args.port)
    REGISTRY.register(TrafficServerCollector(args.endpoint))

    while True:
        time.sleep(1)


if __name__ == '__main__':
    main()
